#!/bin/sh

PAIR=$1
PASS=$2
ALIAS=$3

ROOT_PEM=`mktemp`
CA_PEM=`mktemp`
CHAIN_PEM=`mktemp`

keytool -keystore root.p12 -exportcert -storepass "$PASS" -alias root -rfc > $ROOT_PEM
keytool -keystore operator.p12 -exportcert -storepass "$PASS" -alias kp -rfc > $CA_PEM

CSR=`mktemp`
CERT_PEM=`mktemp`
keytool -storepass "$PASS" -keystore $PAIR -certreq -keyalg EC -alias $ALIAS -ext 'san=dns:*.tower.local,ip:192.168.86.28'   > $CSR
keytool -storepass "$PASS" -keystore operator.p12 -gencert -keyalg EC -alias kp -rfc -ext 'san=dns:*.tower.local,ip:192.168.86.28'   < $CSR > $CERT_PEM

cat $ROOT_PEM $CA_PEM $CERT_PEM > $CHAIN_PEM
keytool -keystore $PAIR -storepass "$PASS" -import -trustcacerts -file $CHAIN_PEM -alias kp -rfc
